---
name: POE-Component-IRC-Plugin-Magic8Ball
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: Magic 8 Ball plugin for IRC
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE::Component::IRC::Plugin::BaseWrap: 0.008
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::Magic8Ball:
    file: lib/POE/Component/IRC/Plugin/Magic8Ball.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
